DOMAIN = "touchline_weather"

CONF_WEATHER_API_KEY = "weather_api_key"
CONF_LATITUDE = "latitude"
CONF_LONGITUDE = "longitude"
CONF_WEATHER_ADAPTATION = "weather_adaptation"
CONF_BASE_TEMP = "base_temperature"
CONF_ADJUSTMENT_FACTOR = "adjustment_factor"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_DEFAULT_ADAPTIVE_DEVICES = "default_adaptive_devices"
CONF_NAME_TEMPLATE = "name_template"
CONF_NAMES = "names"
CONF_COMFORT_TEMPS = "comfort_temperatures"